### PR TITLE
Code Cleanup, Text Correction, Code Optimazation

### PR DESCRIPTION
**Pull request by frogocomics**
I decided to look at your code and I noticed a few improvements that could be made to your code:

Spelling: Some of the spelling in the comments were incorrectly spelled, most notably the word "occurred". I corrected all the spelling.
Java 8: Many Java 8 features were not used, such as lambdas. I changed all anonymous inner classes to lambdas. I also changed code like `HashMap<String, String> map = new HashMap<String, String>();` into `HashMap<String, String> map = new HashMap<>();`.
Code Formatting: I ran my code formatter in Intellj IDEA  and I was able to make the code look overall neater.
Returns: Your code had so much useless return statements. All useless return statements have been removed.
Foreach: I tried to convert code into as much foreach calls as possible for optimization.
TextUtils: I converted all methods of TextUtils into static methods, as there is no need to create new instances of TextUtils.

### CODE REVIEW

**Comment by Flibio** [comment]
EconomyLite 2.0 is about half way done at the moment, and since it a complete rewrite I don't think that this PR is necessary. I will be sure to look at all of the changes you made in this PR and keep them in mind when writing the new version. However, I thank you for taking to time to do this.

**Comment by frogocomics** [comment]
Of course, just remember that formatting is important.

**Comment by Flibio** [comment]
I know, I am currently in the process of updating all of my plugins to use the same formatting.

**Comment by frogocomics** [comment]
Also, you should keep in mind everything I did in my pr, and that your packages shouldn't be capitalized.

**Comment by Flibio** [comment]
That's what I said in my first comment:

> I will be sure to look at all of the changes you made in this PR and keep them in mind when writing the new version.

**Pull request closed without merging**
